### ISSUE TITLE
Timeout for preprocess_cancellation and klipper_estimator is too short

### ISSUE THREAD

**Issue by gjsmo** [pedrolamas/klipper-preprocessor#5]
### What happened

When slicing a large file (~50 objects), `preprocess_cancellation` and `klipper_estimator` may take longer to run than the hardcoded timeout of 10 seconds, generating an error.

### What did you expect to happen

Large files should be correctly processed.

### How to reproduce

I was able to cause this by slicing a file with 50 Benchys. Note that this is on my 8th gen i7 laptop; YMMV as it's obviously dependent on CPU performance.

### Additional information

I increased the timeouts manually to 600 seconds and the file was postprocessed correctly.

**Comment by pedrolamas** [comment]
Hi @gjsmo thank you for reporting this.

The only reason I put a timeout on this was because the Cura UI goes unresponsive while these tools are running, as script execution is not asynchronous.

The 10 seconds limit was just an arbitrary value, but I see now that for more complicated models it might not be enough!

You do make a good point and I will update the default timeout to the proposed 10 minutes (600 seconds)
